---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hono
  name: hono-kafka-broker
  labels:
    app: hono-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-kafka-broker
  template:
    metadata:
      labels:
        app: hono-kafka-broker
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.2.1
          ports:
            - containerPort: 9092
            - containerPort: 9997
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            - name: KAFKA_LISTENERS
              value: 'CONTROLLER://0.0.0.0:29093,PLAINTEXT://0.0.0.0:9092'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://hono-kafka-broker:9092'
            - name: KAFKA_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_NODE_ID
              value: '1'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '1@0.0.0.0:29093'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'PLAINTEXT'
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
          volumeMounts:
            - mountPath: /tmp/update_run.sh
              name: update-run
              subPath: update_run.sh
          command:
            - "bash"
            - "-c"
            - "/tmp/update_run.sh && /etc/confluent/docker/run"
      volumes:
        - name: update-run
          configMap:
            name: hono-kafka-broker-cm
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: hono-kafka-broker
  namespace: hono
spec:
  clusterIP: None
  selector:
    app: hono-kafka-broker
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: hono-kafka-broker-external
  namespace: hono
spec:
  type: NodePort
  selector:
    app: hono-kafka-broker
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      nodePort: 30202
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hono-kafka-broker-cm
  namespace: hono
data:
  update_run.sh: |-
    # This script is required to run kafka cluster (without zookeeper)
    #!/bin/sh

    # Docker workaround: Remove check for KAFKA_ZOOKEEPER_CONNECT parameter
    sed -i '/KAFKA_ZOOKEEPER_CONNECT/d' /etc/confluent/docker/configure

    # Docker workaround: Ignore cub zk-ready
    sed -i 's/cub zk-ready/echo ignore zk-ready/' /etc/confluent/docker/ensure

    # KRaft required step: Format the storage directory with a new cluster ID
    echo "kafka-storage format --ignore-formatted -t $(kafka-storage random-uuid) -c /etc/kafka/kafka.properties" >> /etc/confluent/docker/ensure