apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hono
  name: hono-mongodb
  labels:
    app: hono-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-mongodb
  template:
    metadata:
      name: hono-mongodb
      namespace: hono
      labels:
        app: hono-mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.9
          ports:
            - name: db
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: aaa
---
apiVersion: v1
kind: Service
metadata:
  name: service-db
  namespace: hono
spec:
  selector:
    app: hono-mongodb
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: hono-mongodb-internal
  namespace: hono
spec:
  selector:
    app: hono-mongodb
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017



