version: "3.5"
services:
  mongo:
    image: mongo:5.0.9
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aaa1234
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

