apiVersion: v1
kind: Secret
metadata:
  name: "eclipse-hono-service-device-registry-conf"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "service-device-registry"
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: 1
      auth:
        connectTimeout: 2000
        host: eclipse-hono-service-auth.hono
        hostnameVerificationRequired: false
        port: 5672
        supportedSaslMechanisms: PLAIN
      registry:
        amqp:
          bindAddress: 0.0.0.0
          insecurePortBindAddress: 0.0.0.0
          insecurePortEnabled: true
        http:
          bindAddress: 0.0.0.0
          insecurePortBindAddress: 0.0.0.0
          insecurePortEnabled: true
          authenticationRequired: false
      mongodb:
        dbName: hono-device
        connectionString: mongodb://root:aaa@hono-mongodb-internal.hono
      kafka:
        commonClientConfig:
          bootstrap.servers: hono-kafka-broker.hono:9092
        event:
          producerConfig:
            compression.type: none
        notification:
          producerConfig:
            compression.type: none
    quarkus:
      console:
        color: false
      log:
        min-level: TRACE
        level: INFO
        category:
          "io.quarkus.vertx.core.runtime":
            level: DEBUG
      vertx:
        prefer-native-transport: true
        resolver:
          cache-max-time-to-live: 0
---
apiVersion: v1
kind: Service
metadata:
  name: "eclipse-hono-service-device-registry"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "service-device-registry"
spec:
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: amqp
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/component: "service-device-registry"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eclipse-hono-service-device-registry"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "service-device-registry"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hono"
      app.kubernetes.io/instance: "eclipse-hono"
      app.kubernetes.io/component: "service-device-registry"
  template:
    metadata:
      name: "eclipse-hono-service-device-registry"
      namespace: "hono"
      labels:
        app.kubernetes.io/name: "hono"
        app.kubernetes.io/instance: "eclipse-hono"
        app.kubernetes.io/version: "2.4.0"
        app.kubernetes.io/component: "service-device-registry"

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8088"
        prometheus.io/scheme: "http"
        kubectl.kubernetes.io/default-container: "service-device-registry"

    spec:
      containers:
        - name: "service-device-registry"
          image: "index.docker.io/eclipse/hono-service-device-registry-mongodb:2.4.0"
          ports:
            - name: health
              containerPort: 8088
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: amqps
              containerPort: 5671
              protocol: TCP
            - name: amqp
              containerPort: 5672
              protocol: TCP
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=80"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "QUARKUS_CONFIG_LOCATIONS"
              value: "/opt/hono/default-logging-config/logging-quarkus-dev.yml"
          securityContext:
            privileged: false
          volumeMounts:
            - name: "default-logging-config"
              mountPath: "/opt/hono/default-logging-config"
              readOnly: true
            - name: "service-device-registry-conf"
              mountPath: "/opt/hono/config"
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: 400Mi
            requests:
              cpu: 150m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /liveness
              port: health
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 300
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: health
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: "default-logging-config"
          configMap:
            name: "eclipse-hono-default-logging-config"
            optional: true
        - name: "service-device-registry-conf"
          secret:
            secretName: "eclipse-hono-service-device-registry-conf"