apiVersion: v1
kind: Secret
metadata:
  name: "eclipse-hono-adapter-http-conf"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "adapter-http"
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: 1
      http:
        bindAddress: "0.0.0.0"
        insecurePortBindAddress: "0.0.0.0"
        insecurePortEnabled: true
        tenantIdleTimeout: "1h"
      kafka:
        commonClientConfig:
          bootstrap.servers: "172.31.31.152:9092"
        notification:
          consumerConfig:
            compression.type: none
        command:
          consumerConfig:
            compression.type: none
        commandInternal:
          adminClientConfig:
            compression.type: none
        commandResponse:
          producerConfig:
            compression.type: none
        event:
          producerConfig:
            compression.type: none
        notification:
          consumerConfig:
            compression.type: none
        telemetry:
          producerConfig:
            compression.type: none
      commandRouter:
        host: "eclipse-hono-service-command-router.hono"
        port: 5672
        credentialsPath: "/opt/hono/config/adapter.credentials"
        hostnameVerificationRequired: false  
      registration:
        host: "eclipse-hono-service-device-registry.hono"
        port: 5672
        connectTimeout: 10000
        hostnameVerificationRequired: false
        tlsEnabled: false
        credentialsPath: "/opt/hono/config/adapter.credentials"
      tenant:
        host: "eclipse-hono-service-device-registry.hono"
        port: 5672
        connectTimeout: 10000
        hostnameVerificationRequired: false
        tlsEnabled: false
        credentialsPath: "/opt/hono/config/adapter.credentials"
      credentials:
        host: "eclipse-hono-service-device-registry.hono"
        port: 5672
        connectTimeout: 10000
        hostnameVerificationRequired: false
        tlsEnabled: false
        credentialsPath: "/opt/hono/config/adapter.credentials"
    
    quarkus:
      console:
        color: false
      log:
        min-level: TRACE
        level: INFO
        category:
          "io.quarkus.vertx.core.runtime":
            level: DEBUG
      vertx:
        prefer-native-transport: true
        resolver:
          cache-max-time-to-live: 0
data:
  adapter.credentials: dXNlcm5hbWU9aHR0cC1hZGFwdGVyQEhPTk8KcGFzc3dvcmQ9aHR0cC1zZWNyZXQK
---
apiVersion: v1
kind: Service
metadata:
  name: "eclipse-hono-adapter-http"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    helm.sh/chart: "hono-2.5.1"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "adapter-http"
spec:
  selector:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/component: "adapter-http"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "eclipse-hono-adapter-http"
  namespace: "hono"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: akane.k8s.com
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /http-adapter(/|$)(.*)
            backend:
              service:
                name: eclipse-hono-adapter-http
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eclipse-hono-adapter-http"
  namespace: "hono"
  labels:
    app.kubernetes.io/name: "hono"
    app.kubernetes.io/instance: "eclipse-hono"
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/component: "adapter-http"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hono"
      app.kubernetes.io/instance: "eclipse-hono"
      app.kubernetes.io/component: "adapter-http"
  template:
    metadata:
      name: "eclipse-hono-adapter-http"
      namespace: "hono"
      labels:
        app.kubernetes.io/name: "hono"

        app.kubernetes.io/instance: "eclipse-hono"
        app.kubernetes.io/version: "2.4.0"
        app.kubernetes.io/component: "adapter-http"

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8088"
        prometheus.io/scheme: "http"
        kubectl.kubernetes.io/default-container: "adapter-http"
    spec:
      containers:
        - name: "adapter-http"
          image: "index.docker.io/eclipse/hono-adapter-http:2.4.0"
          ports:
            - name: health
              containerPort: 8088
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          securityContext:
            privileged: false
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=80"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "QUARKUS_CONFIG_LOCATIONS"
              value: "/opt/hono/default-logging-config/logging-quarkus-dev.yml"
          volumeMounts:
            - name: "default-logging-config"
              mountPath: "/opt/hono/default-logging-config"
              readOnly: true
            - name: "adapter-http-conf"
              mountPath: "/opt/hono/config"
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /liveness
              port: health
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 300
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: health
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: "default-logging-config"
          configMap:
            name: "eclipse-hono-default-logging-config"
            optional: true
        - name: "adapter-http-conf"
          secret:
            secretName: "eclipse-hono-adapter-http-conf"
---